#!/usr/bin/env bash

api_url="http://localhost:3333/api"

pwd=$(pwd)
dir=$(basename $pwd)

if [[ $dir -eq "promor" ]]; then
    scripts="$pwd/scripts"
fi

source "$scripts/utils.sh"
source "$scripts/stores.sh"
source "$scripts/pages.sh"

modules=(
    "stores"
    "pages"
)

case $(printf '%s\n' "${modules[@]}" | fzf) in
    "stores") handle_stores;;
    "pages") handle_pages;;
    *) echo "unknown module, exiting";;
esac
